spring:
  application:
    name: kg-builder
  profiles:
    active: dev

  # Neo4j配置
  data:
    neo4j:
      uri: bolt://10.199.87.24:7687  # 这里需要改成你的Neo4j数据库URL
      username: neo4j
      password: 123456  # 这里改成你的Neo4j数据库密码

# MySQL 配置
#  datasource:
#    url: jdbc:mysql://localhost:3306/KG?useSSL=false&serverTimezone=UTC
#    username: root  # 修改为你的 MySQL 用户名
#    password: Qwer1219  # 修改为你的 MySQL 密码
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    url: jdbc:postgresql://10.199.87.24:5432/pg14
    username: pg14  # 用户名
    password: 123456  # 密码
    driver-class-name: org.postgresql.Driver





