server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100000000
      maxRequestSize: 200000000
  thymeleaf:
    cache : false
    mode: HTML5
  neo4j:
      url: bolt://10.199.87.24:7687
      username: neo4j
      password: 123456
  datasource:
#      username: root
#      password: hhuhyt
##      url中database为对应的数据库名称
##      url: jdbc:mysql://192.168.10.83:3306/watercon_mansys?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
#      url: jdbc:mysql://8.218.77.236:3306/watercon_mansys?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&useSSL=false
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/kgdemo?useSSL=false&serverTimezone=UTC
#      driverClassName: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 123456
#      type: com.zaxxer.hikari.HikariDataSource
#       username: postgres
#       password: 441526
##       url中database为对应的数据库名称
#       url: jdbc:postgresql://101.35.42.53:5432/postgres?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
#       driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.199.87.24:5432/pg14
    username: pg14  # 用户名
    password: 123456  # 密码
    driver-class-name: org.postgresql.Driver

mybatis:
  typeAliasesPackage: com.warmer.kgmaker.entity
  mapperLocations: classpath*:/mapping/*.xml
#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql 
#--------七牛云配置
qiniu:
  access:
    key: 2J5BOKpbxDlzkYVYZ5dwGsS3jAevVmOJwcL3fIdpw
  secret:
    key: 2LXAQbFFbFR_I76bseNEmus-Sjnh4RRaSRsazX5Dj
  bucket:
    name: nndt
    host:
      name: file.miaoleyan.com
  prefixName: /nndt
#--------七牛云配置
img:  #//如果是Windows情况下，格式是 D:\\blog\\image\\   linx 格式"/home/blog/image/";
   location : /home/blog/image/
file:
  serverurl:  http://localhost:8080
  location : /home/kgmanager/csv/   #如果是Windows情况下，格式是 D:\\kgmanager\\csv\\   linx 格式"/home/kgmanager/csv/";